### PR TITLE
load/save any step in the annotation history

### LINKED ISSUE #15: Move parsing graphs from string to to graph class
Right now graphs from the API are parsed within the API. Move this to the graph class and add unit tests

### LINKED ISSUE #68: Load and save detailed history
- [x] save any step in `fileAnnotationHistory` to API #70 
- [x] if image loaded with API retrieve history #71 
- [x] if saved only save history until visible point (don't save redo)
- [x] start sync with icon on thumbnail #72 
## if loaded with local mediapie and then connected to API
- [x] load history
- [x] overwrite local annotations

### LINKED ISSUE #70: Allow "infinite" history length
Right now the length of the history is manually specified on developer. This will lead to problems since the history can be kept across multiple sessions

### LINKED ISSUE #71: Load History From server if image is loaded by user

### LINKED ISSUE #72: Overwrite history on clicking the "save" icon

### LINKED ISSUE #73: Remove syncing from the Top bar

### PR DESCRIPTION
**Pull request by Marc-Lorenz**
# Todo
- [x] Test
- [x] Test with API

# Closes
fix #15
fix #68
fix #70
fix #71
fix #72 
fix #73

# Additional fixes
- Change annotation file name `1732698980213_face_mesh_annotations` -> `face_mesh_annotations_2024_11_27_10_16_10_00`

### CODE REVIEW

**Comment by FHellmann** [comment]
- [x] Trim Webservice-URL to remove possible whitespaces at the end/beginning
- [ ] When a Webservice is activated before images are uploaded, it is no longer possible to upload images
- [x] When images are uploaded first and the Webservice is activated afterwards, the history of the annotations is not restored

**Comment by Marc-Lorenz** [comment]
> - [ ] Trim Webservice-URL to remove possible whitespaces at the end/beginning

See #85

> - [ ] When a Webservice is activated before images are uploaded, it is no longer possible to upload images

This fails without any system, sometimes clicking twice it works, but there is no crash or similar

**Review by FHellmann — CHANGES_REQUESTED** [review]
- [x] The drag depth is not considered any longer. When a drag depth > 0 is entered, the neighbouring points are not updated.
- [ ] The change history is not restored from the server as expected. This might be due to the following error: ```Failed to load resource: the server responded with a status of 404 (NOT FOUND)```

**Comment by Marc-Lorenz** [comment]
Please provide an accurate description on the steps on failing, and the image file name. I can't reproduce this

**Comment by Marc-Lorenz** [comment]
The 404 is fixed by Marc-Lorenz@4878f077d8fc0a5b776dc9bfb43fd613813fe8ff

**Review by FHellmann — APPROVED** [review]

**Pull request merged**
