### PR TITLE
Menu rebuild

### LINKED ISSUE #29: Move default options to top bar (Edit, Back Forward, About)

### PR DESCRIPTION
**Pull request by Marc-Lorenz**
- Adds a navbar on the top.
- Makes sidebar content dynamic

depends on #27 

fixes #29

### CODE REVIEW

**Comment by Marc-Lorenz** [comment]
- [x] Fix Zoom Bug

**Comment by FHellmann** [comment]
This is a quick sketch of how the menu should look after the rebuild.

PrototypeFaceMeshEditor drawio

- Accordion: https://getbootstrap.com/docs/5.3/components/accordion/#always-open
- List sorting: https://jqueryui.com/sortable/

**Comment by Marc-Lorenz** [comment]
The dragging to change the order impacts the ability of the drag depth fader. You can only click to change the value

@FHellmann What is the higher priority? Should we change the interface?

**Comment by FHellmann** [comment]
> The dragging to change the order impacts the ability of the drag depth fader. You can only click to change the value
> 
> @FHellmann What is the higher priority? Should we change the interface?

The reordering of the items is less of a priority. Therefore, I'd say to disable this function for now.

**Comment by Marc-Lorenz** [comment]
done

**Comment by FHellmann** [comment]
- [x] Drag depth is only between [1;5] adjustable with SHIFT+Scroll.
- [x] Place drag depth above the category "View".
- [x] Make headings bold so they are more apparent.
- [x] Don't use center alignment for the navbar; use left alignment instead.
- [x] Navbar height should be smaller - the icon can be resized to fit. Orientate on the navbar menu items for height reference.
- [x] The image thumbnail overflow does cut off the last image when many images (more than the display height) are added.

**Review by FHellmann — APPROVED** [review]

**Review by FHellmann — CHANGES_REQUESTED** [review]
- [ ] The image's location and scale factor are passed down when another image is selected. This should be reset to fit the newly selected image to the editor size.

**Review by FHellmann — APPROVED** [review]

**Pull request merged**
